[colors]
table_header_color = "#f5e0dc"
all_cpu_color = "#f5e0dc"
avg_cpu_color = "#eba0ac"
cpu_core_colors = ["#f38ba8","#fab387","#f9e2af","#a6e3a1","#74c7ec","#cba6f7"]
ram_color = "#a6e3a1"
swap_color = "#fab387"
rx_color = "#a6e3a1"
tx_color = "#f38ba8"
widget_title_color = "#f2cdcd"
border_color = "#585b70"
highlighted_border_color = "#f5c2e7"
text_color = "#cdd6f4"
graph_color = "#a6adc8"
cursor_color = "#f5c2e7"
selected_text_color = "#11111b"
selected_bg_color = "#cba6f7"
high_battery_color = "#a6e3a1"
medium_battery_color = "#f9e2af"
low_battery_color = "#f38ba8"
gpu_core_colors = ["#74c7ec","#cba6f7","#f38ba8","#fab387","#f9e2af","#a6e3a1"]
arc_color = "#89dceb"

[flags]
# Whether to hide the average cpu entry.
#hide_avg_cpu = false
dot_marker = false
left_legend = false
#current_usage = false
#unnormalized_cpu = false
group_processes = true
#case_sensitive = false
#whole_word = false
#regex = false
#temperature_type = "k"
#temperature_type = "f"
#temperature_type = "c"
#temperature_type = "kelvin"
#temperature_type = "fahrenheit"
temperature_type = "celsius"
#default_time_value = 60000
#time_delta = 15000
#hide_time = false
#default_widget_type = "proc"
#default_widget_count = 1
#expanded_on_startup = true
#basic = false
#use_old_network_legend = false
#hide_table_gap = false
#battery = false
#disable_click = false

# Valid values are "default", "default-light", "gruvbox", "gruvbox-light", "nord", "nord-light"
#color = "default"

mem_as_value = true
tree = false
#show_table_scroll_position = false
#process_command = false
network_use_binary_prefix = false
network_use_bytes = true
#network_use_log = false
disable_advanced_kill = false
enable_gpu_memory = true
#retention = "10m"
