[flags]
dot_marker = false
left_legend = false
group_processes = true
temperature_type = "celsius"
mem_as_value = true
tree = false
network_use_binary_prefix = false
network_use_bytes = true
disable_advanced_kill = false
enable_gpu_memory = true
