keys:
  - &users: 
    - &glwbr age1q8kpr53cx0wjhp46j3at0k5mggjk36z07h75n0qwa5nsme7su9as9q38sg
  - &hosts:
    - &zion age1v9mvn5dj27sj6rd54hzknvk47j6thepq8w8pzcgxfjsj0jcc0urscc7xzt
creation_rules:
  - path_regex: hosts/shared/secrets.(ya?ml|json)$
    key_groups:
    - age:
      - *glwbr
      - *zion
